### ISSUE TITLE
Admin plugin is not available in the skeleton

### ISSUE THREAD

**Issue by Orcomp** [hibbitts-design/grav-skeleton-learn2-with-git-sync#1]
Thanks for this skeleton. I think the admin plugin is missing from the skeleton.

**Comment by Orcomp** [comment]
My mistake. The error is related to something else. Still investigation

**Comment by Orcomp** [comment]
Find out the problem had to do with using a subdomain. I had to edit the .htaccess file and uncomment the RewriteBase line. Everything working fine now.

**Comment by paulhibbitts** [comment]
Glad that you got it working!
