### ISSUE TITLE
Unable to remove tag

### ISSUE THREAD

**Issue by awrog** [hibbitts-design/grav-skeleton-learn2-with-git-sync#2]
Installed skeleton learn2 v1.1.7 (PHP Version 7.0.30)
After adding a tag to a page (template Docs), I cannot remove it (it returns automatically).
Tried FF and Chrome.
See attachment: 
![remove-tag](https://user-images.githubusercontent.com/12153667/47016817-fef72a00-d150-11e8-9a20-8791619d5ad6.gif)

**Comment by paulhibbitts** [comment]
Thanks for letting me know @awrog , it looks like something to do with the custom blueprint I use for that page type - I will investigate further.

**Comment by paulhibbitts** [comment]
Ok, I think I've found the issue and have a possible fix @awrog 

Could you please replace the contents of the file `learn2-git-sync/blueprints/docs.yaml` with the below and let me know if this works for you? Thanks!

UPDATE: I've included this change in the most recent Learn2 with Git Sync update.

`title: Docs
'@extends':
    type: default
    context: blueprints://pages

form:
  fields:
    tabs:

      fields:
        content:
          type: tab

          fields:

            content:
                markdown: true
                default: "Your page content goes here."

        options:
          fields:
            taxonomies:
              fields:
                header.taxonomy:
                  unset@: true

                header.taxonomy.category:
                  type: selectize
                  label: Category
                  classes: fancy
                  data-default@: '\Grav\Theme\Learn2GitSync::getdefaulttaxonomycategory'
                  validate:
                    type: commalist

                header.taxonomy.tag:
                  type: selectize
                  label: Tag
                  classes: fancy
                  validate:
                    type: commalist

        advanced:
          fields:
            overrides:
              fields:
                header.visible:
                  default: 1
`

**Comment by awrog** [comment]
Apologies for my late reaction.
The new blueprint docs.yaml from release v1.1.8 works as expected!
Thanks

**Comment by paulhibbitts** [comment]
That's great news to hear @awrog , thanks for letting me know.
