### ISSUE TITLE
Can't customize skeleton

### ISSUE THREAD

**Issue by Sogl** [hibbitts-design/grav-skeleton-learn2-with-git-sync#3]
Hello!

Just install this skeleton, set theme to `mytheme` and tried to delete some unuseful plugins for me like `presentation` etc.
Got an error `grav The installed package learn2-git-sync depends on this package. Please remove it first.`

Ok, theme removed. After that I see another error, whole site with admin panel don't work:
![image](https://user-images.githubusercontent.com/7556290/60402549-030d8f80-9b9a-11e9-953a-358c6b48d558.png)

How to customize? )

**Comment by paulhibbitts** [comment]
Hi @Sogl , the Learn2 with Git Sync has a number of Plugins set as dependencies, and if you remove those items manually I would expect things not to work etc. If you do not want to include the required Plugins in your site perhaps another skeleton/theme would be a better choice?

**Comment by Sogl** [comment]
Some of your `Learn2` theme changes is interesting for me (main logo, Github link to GitSync link etc). But seems I can't use it without bunch of plugins.

**Comment by paulhibbitts** [comment]
Please feel free to use the parts of interest in your own inherited theme of Learn2 etc. I am sure my Twig could also be improved etc🙂https://github.com/hibbitts-design/grav-theme-learn2-git-sync

You can contact me directly in the Grav Discord room too with further questions etc. https://getgrav.org/discord

**Comment by Sogl** [comment]
Moving this dialog to Discord, thx
