### ISSUE TITLE
'Top Level Version'= TRUE causes simple search to stop displaying page in menu

### ISSUE THREAD

**Issue by awrog** [hibbitts-design/grav-skeleton-learn2-with-git-sync#6]
After implementing 'Top Level Version'= TRUE succesfully my users have noticed that **Simple Search** does not show the right page in the menu (and does not expand the menu)

Below the behavior with  'Top Level Version'= FALSE

![simplesearch](https://user-images.githubusercontent.com/12153667/70036783-bc431c00-15b5-11ea-84e3-9e5968d82d0d.gif)

**Comment by paulhibbitts** [comment]
Thanks for reporting the issue, does this also occur in the parent Learn2 theme?

**Comment by awrog** [comment]
The parent theme works as expected (hoped for).
I sure hope you can fix this!!

![learn2-simple-search](https://user-images.githubusercontent.com/12153667/70126399-37b9d180-1679-11ea-8356-1ae56d4e94c3.gif)

**Comment by paulhibbitts** [comment]
Hi @awrog , starting with a cleared history state I cannot seem to get the desired behaviour with the Learn2 parent theme. One thing to try though is to use the default Learn2 CSS theme style vs. the modified versions provided in the Learn2 with Git Sync theme.

<img width="1221" alt="2019-12-04_08-21-53" src="https://user-images.githubusercontent.com/1812771/70160340-34214d00-166f-11ea-9434-025edb3a9aec.png">

Another possibility is to use the Advanced Search feature of Learn2 with Git Sync vs. the Simple Search. To do this enable the included TNTSearch Plugin, which then should result in an "Advanced Search" link beneath the SimpleSearch field.

Please let me know how the above goes.

**Comment by awrog** [comment]
Paul,
I also am unable to reproduce.
Did two fresh installs and both will not jump to the right page in the navigation.
TNTsearch works for me, a pity though it does not do highlighting when you open a page from the search result.

Might I suggest adding a condition in search.html.twig to hide the simplesearch inputfield? currently it is displayed always, even if the simplesearch plugin is not installed

{% if config.plugins.simplesearch.enabled %}
....
{% endif %}
{% if config.plugins.tntsearch.enabled %}
....
{% endif %}

**Comment by paulhibbitts** [comment]
Great catch on that @awrog , I will update the theme - here is how things look:
<img width="1200" alt="2019-12-05_08-50-33" src="https://user-images.githubusercontent.com/1812771/70256678-ba0bc980-173d-11ea-988f-a2865b563e7a.png">

Note that you can change the "Advanced Full-text Search" text string in the `languages.yaml` file of the Learn2 with Git Sync theme. I will release this update in the next few hours.

UPDATE: Theme update is now available via Grav.

**Comment by paulhibbitts** [comment]
I am closing this, but please feel free to re-open if needed.
